- name: test inventory
  hosts: all
  tasks:
    - name: print my variable
      ansible.builtin.debug:
        var: name 
    - name: print by other variable
      ansible.builtin.debug:
        var: group         

# ansible-playbook -i hosts main.yaml        